# -*- coding: utf-8 -*-
"""RF_APK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19On4oYqRMEVJZENRP13tU_HPMiXaRwjx

# 🔌 Estimasi Panjang Kabel Instalasi Listrik dengan Random Forest Regressor
**Tujuan:** Memprediksi nilai `cableLength` dari data spesifikasi instalasi rumah tinggal  
**Output:** Model prediksi
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Muat model
model = joblib.load('model_rf_ahs.pkl')

st.title("Prediksi Panjang Kabel Penerangan - AHS")

# Input harga material
st.sidebar.header("Setting Harga Material")
harga_nym_per_m = st.sidebar.number_input("Harga NYM 2 x 2,5 per meter", min_value=0, value=20000)
harga_pipa_per_m = st.sidebar.number_input("Harga Pipa Conduit 20mm per meter", min_value=0, value=4200)
harga_sock_per_pcs = st.sidebar.number_input("Harga Sock conduit 20mm per pcs", min_value=0, value=1100)
harga_klem_per_pcs = st.sidebar.number_input("Harga Klem conduit 20mm per pcs", min_value=0, value=1100)
harga_teedos_per_pcs = st.sidebar.number_input("Harga Teedos 20mm per pcs", min_value=0, value=9000)
harga_flexible_per_m = st.sidebar.number_input("Harga Flexible 20mm per meter", min_value=0, value=6500)
harga_sekrup_fisher_per_pcs = st.sidebar.number_input("Harga Sekrup dan Fisher per pcs", min_value=0, value=500)

# Membuat layout responsif
with st.container():
    col1, col2 = st.columns([1, 1])

    with col1:
        st.header("Input Data")
        rooms = st.number_input("Jumlah Ruangan", min_value=1, max_value=10, value=1)
        surfaces = st.number_input("Jumlah Permukaan m2", min_value=1, max_value=500, value=15)
        height = st.number_input("Tinggi Bangunan (m)", min_value=1, max_value=100, value=3)
        spotlight = st.number_input("Jumlah Spotlight", min_value=0, max_value=100, value=2)
        downlight = st.number_input("Jumlah Downlight", min_value=0, max_value=100, value=3)
        pendant = st.number_input("Jumlah Pendant", min_value=0, max_value=100, value=0)

        # Hitung total lampu otomatis
        totLamps = spotlight + downlight + pendant
        st.write("Total Lampu (otomatis dihitung):", totLamps)

        # Tombol prediksi
        if st.button("Prediksi Kabel Length"):
            input_data = pd.DataFrame({
                'rooms': [rooms],
                'surfaces': [surfaces],
                'height': [height],
                'spotlight': [spotlight],
                'downlight': [downlight],
                'pendant': [pendant],
                'totLamps': [totLamps]
            })

            pred = model.predict(input_data)[0]

            # Hitung jumlah titik kabel (jumlah titik lampu)
            cable_point = np.ceil(pred / totLamps)

            # Hitung komponen harga berdasarkan jumlah titik lampu
            total_harga_nym = pred * harga_nym_per_m
            pipa_conduit = cable_point - 1
            total_harga_pipa = pipa_conduit * totLamps * harga_pipa_per_m
            sock_pcs = np.ceil(pipa_conduit / 2)
            total_harga_sock = sock_pcs * totLamps * harga_sock_per_pcs
            klem_pcs = np.ceil(pipa_conduit)
            total_harga_klem = klem_pcs * totLamps * harga_klem_per_pcs
            total_harga_teedos = totLamps * harga_teedos_per_pcs
            total_harga_flexible = totLamps * harga_flexible_per_m
            sekrup_fisher = (klem_pcs + 1) * 2 * totLamps
            total_harga_sekrup = sekrup_fisher * harga_sekrup_fisher_per_pcs

            # Hitung total harga
            total_harga = (
                total_harga_nym +
                total_harga_pipa +
                total_harga_sock +
                total_harga_klem +
                total_harga_teedos +
                total_harga_flexible +
                total_harga_sekrup
            )

            # Tampilkan hasil prediksi
            with col2:
                st.header("Hasil Prediksi")
                st.success(f"Perkiraan Kabel Length yang Dibutuhkan: {pred:.2f} meter")
                st.write(f"**Total Harga Material:**")
                # Area latar belakang merah muda
                st.markdown(
                    f"""
                    <div style="background-color:#ffccf9;padding:10px;border-radius:10px;">
                        Rp {total_harga:,.0f}
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                # Rincian material
                st.write(f"**Rincian Kebutuhan per titik:**")
                cable_point = np.ceil(pred / totLamps)
                st.write(f"- NYM 2 x 2,5 : {cable_point:.2f} m")
                pipa_conduit = cable_point - 1
                st.write(f"- Pipa conduit 20 mm : {pipa_conduit:.2f} m")
                sock_pcs = np.ceil(pipa_conduit / 2)
                st.write(f"- Sock conduit 20 mm : {int(sock_pcs)} pcs")
                klem_pcs = np.ceil(pipa_conduit)
                st.write(f"- Klem conduit 20 mm : {int(klem_pcs)} pcs")
                teedos_pcs = 1
                st.write(f"- Teedos 20 mm : {teedos_pcs} pcs")
                flexible = 1
                st.write(f"- Flexible 20 mm : {flexible} m")
                sekrup_fisher = (klem_pcs + teedos_pcs) * 2
                st.write(f"- Sekrup dan Fisher : {int(sekrup_fisher)} pcs")