# -*- coding: utf-8 -*-
"""RF_APK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19On4oYqRMEVJZENRP13tU_HPMiXaRwjx

# 🔌 Estimasi Panjang Kabel Instalasi Listrik dengan Random Forest Regressor
**Tujuan:** Memprediksi nilai `cableLength` dari data spesifikasi instalasi rumah tinggal  
**Output:** Model prediksi + tabel kontribusi fitur (AHS) + metrik evaluasi
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Muat model
model = joblib.load('model_rf_ahs.pkl')

st.title("Prediksi Panjang Kabel Penerangan - AHS")

# Membuat dua kolom
col1, col2 = st.columns(2)

# Area input di kolom kiri
with col1:
    st.header("Input Data")
    # Mengambil input dari pengguna
    rooms = st.number_input("Jumlah Ruangan (rooms)", min_value=1, max_value=10, value=1)
    surfaces = st.number_input("Luas Permukaan (surfaces)", min_value=1, max_value=200, value=17)
    spotlight = st.number_input("Jumlah Spotlight", min_value=0, max_value=50, value=5)
    downlight = st.number_input("Jumlah Downlight", min_value=0, max_value=50, value=3)
    pendant = st.number_input("Jumlah Pendant", min_value=0, max_value=50, value=0)
    totLamps = st.number_input("Jumlah Lampu", min_value=1, max_value=50, value=3)
    lampCableLength = st.number_input("Panjang Kabel Lampu", min_value=0, max_value=200, value=15)

    # Tombol untuk melakukan prediksi atau proses
    if st.button("Hitung Hasil"):

        # Contoh proses (misalnya prediksi atau perhitungan)
        # Jika menggunakan model:
        # input_data = pd.DataFrame({
        #     'rooms': [rooms],
        #     'surfaces': [surfaces],
        #     'spotlight': [spotlight],
        #     'downlight': [downlight],
        #     'pendant': [pendant],
        #     'totLamps': [totLamps],
        #     'lampCableLength': [lampCableLength]
        # })

        # result = model.predict(input_data)

        # Untuk contoh, kita buat hasil dummy
        hasil = f"Data Input:\n- Ruangan: {rooms}\n- Surfaces: {surfaces}\n- Spotlight: {spotlight}\n- Downlight: {downlight}\n- Pendant: {pendant}\n- Total Lamps: {totLamps}\n- Panjang Kabel: {lampCableLength} cm\n\n[Hasil prediksi atau analisis akan muncul di sini]"

# Area hasil di kolom kanan
with col2:
    st.header("Hasil")
    st.write(hasil)